config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  get "welcome/say_hello" => "welcome#say"

  # root "articles#index"

  resources :posts do
  resources :comments, except: :show
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true

  has_many :post_category_ships
  has_many :posts, through: :post_category_ships
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence:true
  validates :contact_number, presence:true

  has_many :post_category_ships
  has_many :categories, through:  :post_category_ships
  has_many :comments

end

app/models/post_category_ship.rb
class PostCategoryShip < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_up_path_for(resource)
    after_sign_in_path_for(resource) if is_navigational_format?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_comment, only: [:edit, :update, :destroy]

  def index
    @comments = @post.comments
  end

  def new
    @comment = @post.comments.build
  end

  def create
    @comment = @post.comments.build(params_comment)
    if @comment.save
      redirect_to post_comments_path(@post)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @comment.update(params_comment)
      redirect_to post_comments_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to post_comments_path(@post)
  end

  private

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

  def set_post
    @post = Post.find params[:post_id]
  end

  def params_comment
    params.require(:comment).permit(:content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    # @post.user = current_user
    if @post.save
      redirect_to posts_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show

  end

  def edit;

  end

  def update
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:first_name, :last_name, :email, :contact_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper

end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_with model: comment, url: path, data: { turbo: false } do |form| %>
  <% if comment.errors.any? %>
    <ul>
      <% comment.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>
  <div>
    <div>
      <%= form.label :content %>
      <%= form.text_field :content, placeholder: "Comment"%>
    </div>
  </div>
  <%= form.submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Title: <%= @post.first_name %></h1>
<h2>edit comment id: <%= @comment.id %></h2>
<%= render partial: 'form', locals: {post: @post, comment: @comment,  path: post_comment_path(@post, @comment)} %>

app/views/comments/index.html.erb
<h1>Title <%= @post.first_name %></h1>
<h2>Comments</h2>
<ul>
  <% @comments.each do |comment| %>
    <li>
    <%= comment.content %>(<%= comment.created_at %>)
    <%= link_to 'edit', edit_post_comment_path(@post, comment) %>
    <%= button_to 'delete', post_comment_path(@post, comment), method: :delete %>
    </li>
    <div>
    <%= link_to 'Index', posts_path(@post) %>
    </div>
  <% end %>

</ul>

app/views/comments/new.html.erb
<h1>Title:
  <% @post.first_name %></h1>
<%= render partial: 'form', locals: {post: @post, comment: @comment, path: post_comments_path(@post)} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L u n a &#x1D19; i e | Welcome </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <div  class="navbar">
      <header>
        <div class="container" >
          <h1 class="logo"><i class="fa-solid fa-star-and-crescent" ></i>L u n a &#x1D19; i e </h1>
          <ul>
            <li><a href="https://www.google.com/" > Home&nbsp&nbsp </a></li>
            <li><a href="#" target="_blank"> Contact&nbsp&nbsp  </a></li>
            <li><a href="#" > About Us&nbsp&nbsp </a></li>
          </ul>
        </div>
      </header>
    </div>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="*notice*"><%= notice %></p>
  <p class="*alert*"><%= alert %></p>
    <%= yield %>
  </body>

  <footer class="main-footer">
    <p> Luna&#x1D19ie Spa & Hotel&nbsp 2022,&nbsp; All Rights Reserved</p>
  </footer>

</html>

app/views/posts/_form.html.erb
<%= form_with model: post do |form| %>
  <% if post.errors.any? %>
    <ul>
      <% post.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>
    <div>
      <%= form.label :first_name, class: 'f_name'%>
      <%= form.text_field :first_name, placeholder: 'First Name' %>
    </div>
    <div>
      <%= form.label :last_name, class: "l_name" %>
      <%= form.text_field :last_name, placeholder: 'Last Name' %>
    </div>
    <div>
      <%= form.label :email, class: 'email' %>
      <%= form.text_field :email, placeholder: "Email"%>
    </div>
    <div>
      <%= form.label :contact_number %>
      <%= form.text_field :contact_number, placeholder: "Contact Number"%>
    </div>
      <%= form.submit %>
<% end %>

app/views/posts/edit.html.erb
  <h1>Edit Post id: <%= @post.id %></h1>


  <%= render partial: 'form', locals: { post: @post } %>

  <%= link_to 'Index', posts_path %>

app/views/posts/index.html.erb
<h1> Post List</h1>

<table>
  <thead>
  <td>First Name</td>
  <td>Last Name</td>
  <td>Email</td>
  <td>Contact</td>
  <td>Change</td>
  <td>User</td>
  </thead>
  <% @posts.each do |post| %>
  <tr>
    <td><a class="f_name1"><%= post.first_name %></a>
    <td><a class="l_name1"><%= post.last_name %></a>
    <td><a class="email1"><%= post.email %></a>
    <td><a class="c_number1"><%= post.contact_number%></a></td>
<!--    <td><%#= post.user&.email %></td>-->
    <td>
    <%= link_to 'Show', post_path(post) %>
    <%= link_to 'Edit', edit_post_path(post) %>
    <%= link_to 'new comment', new_post_comment_path(post) %>
    <%= button_to 'Delete', post_path(post), method: :delete %>
    </td>
  </tr>
  <% end %>


  <%= link_to 'New', new_post_path %>

</table>

</html>

app/views/posts/new.html.erb
<%= form_with model: @post do |form| %>
  <div class="container1">
    <h2>Booking Post</h2>
    <%= render partial: 'form', locals: { post: @post } %>
  </div>
  <div class="container2">
    <button class="btn"><%= link_to 'Index', posts_path %></button>
  </div>


<% end %>

app/views/posts/show.html.erb
<h1>Show List Id: <%= @post.id %></h1>
<div class="container2">
  <ul>
    <li><%= @post.first_name %></li>
    <li><%= @post.last_name %></li>
    <li><%= @post.email %></li>
    <li><%= @post.contact_number%></li>
  </ul>
</div>

app/views/posts/update.html.erb
<h1>Update Post id: <%= @post.id %></h1>
<% if @post.errors.any? %>
  <ul>
    <% @post.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @post do |form| %>
  <div>
    <%= form.label :first_name, class: 'f_name' %>
    <%= form.text_field :first_name %>
  </div>
  <div>
    <%= form.label :last_name, class: "l_name" %>
    <%= form.text_field :last_name %>
  </div>
  <div>
    <%= form.label :email, class: 'email' %>
    <%= form.text_field :email%>
  </div>
  <div>
    <%= form.label :contact_number %>
    <%= form.text_field :contact_number%>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to 'Index', posts_path %>

app/views/welcome/say.html.erb
<h1>Hello, World!</h1>